### ISSUE TITLE
ConfigFactory receives an instance of Container instead of expected ContainerBuilder

### ISSUE THREAD

**Issue by gorkaio** [proophsoftware/prooph-interop-bundle#2]
I'm trying to use prooph/service-bus in a Symfony2.8 application, with prooph-interop-bundle as a bridge. The steps I've followed:

`composer require prooph/service-bus`

`composer require proophsoftware/prooph-interop-bundle`

`composer require sandrokeil/interop-config:^0.3`

(`sandrokeil/interop-config:^0.3` is explicitly required so 1.0 won't get installed, as it breaks `prooph/service-bus` because of the `RequiresContainerId` removal)

app/config/parameters.yml:

``` yml
parameters:
  interop_config: ['prooph']
```

app/config/config.yml:

``` yml
prooph_interop:
  service_bus:
    command_bus:
      router:
        routes:
          ...
    event_bus:
      router:
        routes:
          ...
```

app/AppKernel:

``` php
class AppKernel extends Kernel
{
  public function registerBundles()
  {
    $bundles = [
      ...,
      new \Prooph\InteropBundle\ProophInteropBundle()
    ];
    ...
  }
  ...
}
```

service_bus.yml

``` yml
services:
  prooph.service_bus.command_bus.factory:
    class: Prooph\ServiceBus\Container\CommandBusFactory

  prooph.service_bus.command_bus:
    class: Prooph\ServiceBus\CommandBus
    factory: ['@prooph.service_bus.command_bus.factory', '__invoke']
    arguments:
      - '@interop_container'

  prooph.service_bus.event_bus.factory:
    class: Prooph\ServiceBus\Container\EventBusFactory

  prooph.service_bus.event_bus:
    class: Prooph\ServiceBus\EventBus
    factory: ['@prooph.service_bus.event_bus.factory', '__invoke']
    arguments:
      - '@interop_container'
```

When running the application, the following fatal error is thrown:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Prooph\InteropBundle\Container\ConfigFactory::__invoke() must be an instance of Symfony\Component\DependencyInjection\ContainerBuilder, instance of appDevProjectContainer given, called in /var/www/.../var/cache/dev/appDevProjectContainer.php on line 273 in /var/www/.../vendor/proophsoftware/prooph-interop-bundle/src/Container/ConfigFactory.php:27
Stack trace:
#0 /var/www/.../var/cache/dev/appDevProjectContainer.php(273): Prooph\InteropBundle\Container\ConfigFactory->__invoke(Object(appDevProjectContainer))
#1 /var/www/.../vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(316): appDevProjectContainer->getConfigService()
#2 /var/www/.../vendor/proophsoftware/prooph-interop-bundle/src/Container/InteropContainer.php(40): Symfony\Component\DependencyInjection\Container->get('config')
#3 /var/www/.../vendor/p in /var/www/.../vendor/proophsoftware/prooph-interop-bundle/src/Container/ConfigFactory.php on line 27
```

I'm guessing it has something to do with Symfony's compiler pass, but I haven't been able to find a solution yet.
